version: "3"

services:
  app:
    build: .
    container_name: app
    volumes:
      - ./taxi/:/src/taxi:rw
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - database
    command: python ./taxi/manage.py runserver 0.0.0.0:8000
      
  database:
    container_name: taxi_db
    image: postgres:14.2
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: taxi_db
      POSTGRES_PORT: 5432
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432